// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateDependencyGraph(arg1) {
  return window['go']['app']['App']['GenerateDependencyGraph'](arg1);
}

export function OpenSelectFolderDialog(arg1) {
  return window['go']['app']['App']['OpenSelectFolderDialog'](arg1);
}
