// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateDependencyGraphJSON(arg1) {
  return window['go']['app']['App']['GenerateDependencyGraphJSON'](arg1);
}

export function GenerateDependencyGraphSVG(arg1) {
  return window['go']['app']['App']['GenerateDependencyGraphSVG'](arg1);
}

export function OpenDirectoryDialog(arg1) {
  return window['go']['app']['App']['OpenDirectoryDialog'](arg1);
}
