// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function GenerateDependencyGraph(arg1:app.GraphGenerationOptions):Promise<app.Graph>;

export function GenerateDependencyGraphSVG(arg1:app.Graph):Promise<string>;

export function OpenDirectoryDialog(arg1:app.OpenDialogOptions):Promise<string>;
