// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConflictRule(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['AddConflictRule'](arg1, arg2, arg3, arg4, arg5);
}

export function AnalyzeModpack(arg1) {
  return window['go']['app']['App']['AnalyzeModpack'](arg1);
}

export function DeleteConflictRule(arg1) {
  return window['go']['app']['App']['DeleteConflictRule'](arg1);
}

export function GetConflictRules() {
  return window['go']['app']['App']['GetConflictRules']();
}

export function GetDependencyGraph(arg1) {
  return window['go']['app']['App']['GetDependencyGraph'](arg1);
}

export function GetModMetadata(arg1) {
  return window['go']['app']['App']['GetModMetadata'](arg1);
}

export function GetModpackStatus(arg1) {
  return window['go']['app']['App']['GetModpackStatus'](arg1);
}

export function QuickScan(arg1) {
  return window['go']['app']['App']['QuickScan'](arg1);
}

export function RefreshModpack(arg1) {
  return window['go']['app']['App']['RefreshModpack'](arg1);
}

export function ScanModpack(arg1) {
  return window['go']['app']['App']['ScanModpack'](arg1);
}

export function Startup(arg1) {
  return window['go']['app']['App']['Startup'](arg1);
}
