// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function GenerateDependencyGraphJSON(arg1:app.GraphOptions):Promise<string>;

export function GenerateDependencyGraphSVG(arg1:app.GraphOptions):Promise<string>;

export function OpenDirectoryDialog(arg1:app.OpenDialogOptions):Promise<string>;
