// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {models} from '../models';
import {context} from '../models';

export function AddConflictRule(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function AnalyzeModpack(arg1:string):Promise<services.AnalysisReport>;

export function DeleteConflictRule(arg1:number):Promise<void>;

export function GetConflictRules():Promise<Array<models.ConflictRule>>;

export function GetDependencyGraph(arg1:string):Promise<models.Graph>;

export function GetModMetadata(arg1:string):Promise<models.ModMetadata>;

export function GetModpackStatus(arg1:string):Promise<services.ScanResult>;

export function OnBeforeClose(arg1:context.Context):Promise<boolean>;

export function OpenDirectoryDialog():Promise<string>;

export function QuickScan(arg1:string):Promise<services.ScanResult>;

export function RefreshModpack(arg1:string):Promise<services.ScanResult>;

export function ScanModpack(arg1:string):Promise<services.ScanResult>;

export function Startup(arg1:context.Context):Promise<void>;
